variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - release

build:
  image: texlive/texlive
  stage: build
  script:
    - xelatex main.tex
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - "*.pdf"
    expire_in: 1d
    reports:
      dotenv: job.env
  except:
    - tags

release:
  image: registry.gitlab.com/gitlab-org/release-cli
  stage: release
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Create Release $CI_COMMIT_SHA"
  release:
    name: "Release $CI_COMMIT_SHA"
    tag_name: "release-$CI_COMMIT_SHA"
    ref: "$CI_COMMIT_SHA"
    description: "Release $CI_COMMIT_SHA"
    assets:
      links:
        - name: "main.pdf"
          url: "https://git.karaolidis.com/karaolidis/cv/-/jobs/$JOB_ID/artifacts/raw/main.pdf"
  except:
    - tags
