name: Generate PDF Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Create Release Tag
        id: create_tag
        run: echo ::set-output name=tag::v${{ github.run_number }}
      - name: Push Tag to GitHub
        run: git tag ${{ steps.create_tag.outputs.tag }} && git push origin ${{ steps.create_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.PATTOKEN }}
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: MyCV.pdf
          tag_name: ${{ steps.create_tag.outputs.tag }} # Use the tag generated in the previous step
        env:
          GITHUB_TOKEN: ${{ secrets.PATTOKEN }}
          GITHUB_REPOSITORY: panostriantafyllidis/MyCV_LaTeX
