name: Build and Release

on:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch: # Add manual triggering

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        texlive-version: [full, small] # You can specify different versions here if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: MyCV.tex
          texlive_version: ${{ matrix.texlive-version }}

      - name: Compile LaTeX document
        run: |
          xelatex MyCV.tex

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: pdf
          path: |
            MyCV.pdf
            job.env

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download PDF artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: pdf
          path: build

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Release ${{ github.sha }}
          tag: release-${{ github.sha }}
          body: "Release ${{ github.sha }}"
          token: ${{ secrets.PATTOKEN }}

      - name: Upload PDF as release asset
        uses: softprops/action-gh-release@v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/MyCV.pdf
          name: MyCV.pdf
          token: ${{ secrets.PATTOKEN }}
        env:
          GITHUB_REPOSITORY: panostriantafyllidis/MyCV_LaTeX
