name: Weekly Build and Release

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  build:
    name: Build CV
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up TeX Live on Windows
        uses: xu-cheng/latex-action/setup-texlive@v2
        with:
          latex-version: "2021"

      - name: Compile CV
        run: latexmk -pdf MyCV.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: MyCV
          path: MyCV.pdf
