name: Generate PDF Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        id: upload-release-asset
        with:
          files: MyCV.pdf
        env:
          GITHUB_REPOSITORY: mpanostriantafyllidis/MyCV_LaTeX
