name: Generate PDF Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        id: upload-release-asset
        with:
          files: MyCV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: panostriantafyllidis/MyCV_LaTeX
