name: Build and Release LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Prepare LaTeX packages
        run: |
          mkdir -p texmf/tex/latex/siunitx
          wget -O texmf/tex/latex/siunitx/siunitx.sty https://ctan.org/tex-archive/macros/latex/contrib/siunitx/siunitx.sty
          # Download any other required files for siunitx package if needed
          # e.g., wget -O texmf/tex/latex/siunitx/siunitx.def https://ctan.org/tex-archive/macros/latex/contrib/siunitx/siunitx.def

      - name: Compile LaTeX CV
        run: xelatex MyCV.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: MyCV.pdf

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Get Job ID
        run: echo "JOB_ID=$GITHUB_RUN_ID" >> job.env

      - name: Upload job.env as artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-env
          path: job.env

      - name: Get Artifact URL
        id: get_artifact_url
        run: echo "::set-output name=artifact_url::$(echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/artifacts")"

      - name: Publish Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MyCV.pdf
          asset_name: MyCV.pdf
          asset_content_type: application/pdf

      - name: Save Release URL
        run: echo "RELEASE_URL=${{ steps.upload-release-asset.outputs.browser_download_url }}" >> job.env

      - name: Upload Release URL
        uses: actions/upload-artifact@v2
        with:
          name: release-url
          path: job.env

      - name: Cleanup
        run: |
          rm -f job.env
