name: Generate PDF Release

on:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch: # Add manual triggering

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: MyCV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.PATTOKEN }}
          GITHUB_REPOSITORY: panostriantafyllidis/MyCV_LaTeX
