name: Build and Release LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX environment
        run: |
          choco install texlive
          export PATH="$PATH:/c/Program Files/TexLive/2021/bin/win32"

      - name: Prepare LaTeX packages
        run: |
          mkdir -p texmf\tex\latex\siunitx
          wget -O texmf\tex\latex\siunitx\siunitx.sty https://ctan.org/tex-archive/macros/latex/contrib/siunitx/siunitx.sty
          wget -O texmf\tex\latex\siunitx\siunitx-abbrev.sty https://ctan.org/tex-archive/macros/latex/contrib/siunitx/siunitx-abbrev.sty

      - name: Compile LaTeX CV
        run: |
          xelatex -output-directory=output MyCV.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: output/MyCV.pdf

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload PDF as Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/MyCV.pdf
          asset_name: MyCV.pdf
          asset_content_type: application/pdf
